---
# Source: opentelemetry-demo/templates/component.yaml
apiVersion: v1
kind: Service # Defines a Service type resource
# Metadata for the Service type resource
metadata:
  name: opentelemetry-demo-productcatalogservice
  # labels used for organization and selection
  # these labels are for identifying the application and its version
  labels:
    opentelemetry.io/name: opentelemetry-demo-productcatalogservice
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/component: productcatalogservice
    app.kubernetes.io/name: opentelemetry-demo-productcatalogservice
    app.kubernetes.io/version: "1.12.0"
    app.kubernetes.io/part-of: opentelemetry-demo
# Specification of the Service type resource
spec:
  type: ClusterIP # Service type is ClusterIP
  ports:
    - port: 8080 # Port exposed by the Service
      name: tcp-service # Name of the port
      targetPort: 8080 # Target port on which the application listens (pods)
  selector: # Selector to identify the pods targeted by this Service
    opentelemetry.io/name: opentelemetry-demo-productcatalogservice
